import './modal.js';
import './menu.js';
import './sidebar.js';
import './render.js';
import './api-request.js';
// import './shopping.js';
import './support.js';
import './container.js';
import './scrollUp.js';
import './loader.js';
